#!/bin/bash

libpath=`rtai-config --library-dir`

if [ "$libpath" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** PLANT TASK ***"
echo "Press <enter> to load LXRT modules:"
read junk
./ldmod
echo
echo "Now start the realtime process <enter>:"
read junk
./plant
echo "Done. Press <Ctrl-C> to kill the process, then ./remod to clean-up"
